export const ADD_TRANSACTION = 'ADD_TRANSACTION'
export const FETCH_TRANSACTION = 'FETCH_TRANSACTION'
export const FETCH_BALANCE = 'FETCH_BALANCE'
export const FETCH_INFO_COUNT_OF_TRANSACTION = 'FETCH_INFO_COUNT_OF_TRANSACTION'
export const INTERVAL_GET_BALANCE = 3000
export const INTERVAL_GET_INFO_TRANSACTION = 500
export const INTERVAL_UPDATE_TRANSACTIONS_TABLE = 3000